# Generated by Django 5.2.4 on 2025-08-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_city_rename_preferred_date_wasterequest_pickup_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_dates', to='api.city')),
            ],
        ),
    ]
