# Generated by Django 5.2.4 on 2025-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('waste_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('frequency', models.CharField(max_length=20)),
                ('urgency', models.CharField(max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('base_price', models.FloatField()),
                ('additional_charges', models.FloatField(default=0)),
                ('final_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
