# Generated by Django 5.2.4 on 2025-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wasteorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteOrder',
        ),
        migrations.RenameField(
            model_name='wasterequest',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='wasterequest',
            name='pickup_date',
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='additional_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='final_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on Pickup', 'Cash on Pickup'), ('UPI', 'UPI'), ('Card', 'Card')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='urgency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='waste_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
