# Generated by Django 5.2.4 on 2025-08-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_wasteorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
