# Generated by Django 5.2.4 on 2025-08-12 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_base_price_wasterequest_gstamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('On the Way', 'On the Way'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waste_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.wasterequest')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
