# Generated by Django 5.2.4 on 2025-08-12 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_wasterequeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequeststatus',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='wasterequeststatus',
            unique_together={('waste_request', 'pickup_date')},
        ),
    ]
