# Generated by Django 5.2.4 on 2025-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_wasterequeststatus_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='pickup_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
