# Generated by Django 5.2.4 on 2025-08-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_wasterequest_pickup_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequeststatus',
            name='pickup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wasterequeststatus',
            name='waste_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.wasterequest'),
        ),
    ]
