# Generated by Django 5.2.4 on 2025-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_wasterequeststatus_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequeststatus',
            name='waste_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='wasterequeststatus',
            name='waste_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
