# Generated by Django 5.2.4 on 2025-08-18 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_invoice_updatedwasterequest_invoice_related_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequestPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('waste_type', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gstAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waste_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='api.wasterequest')),
            ],
        ),
        migrations.AlterField(
            model_name='adjustmentinvoice',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='api.wasterequestpickup'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wasterequestpickup'),
        ),
        migrations.DeleteModel(
            name='UpdatedWasteRequest',
        ),
    ]
