# Generated by Django 5.2.4 on 2025-08-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_wasterequestuserupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='gstAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
