# Generated by Django 5.2.4 on 2025-08-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_wasterequest_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequestCancelled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('waste_type', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('final_amount', models.FloatField(default=0)),
                ('cancelled_by', models.CharField(choices=[('User', 'User'), ('Staff', 'Staff'), ('Admin', 'Admin')], max_length=10)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('waste_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_pickups', to='api.wasterequest')),
            ],
            options={
                'unique_together': {('waste_request', 'pickup_date')},
            },
        ),
    ]
