# Generated by Django 5.2.4 on 2025-08-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_wasterequestcancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequestuserupdate',
            name='waste_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updates', to='api.wasterequest'),
        ),
    ]
