# Generated by Django 5.2.4 on 2025-08-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_wasterequestuserupdate_waste_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='additional_charges',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gst_amount',
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='invoice_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.wasterequest'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='related_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wasterequestuserupdate'),
        ),
        migrations.AlterField(
            model_name='wasterequestuserupdate',
            name='waste_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wasterequest'),
        ),
    ]
