# Generated by Django 5.2.4 on 2025-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_invoice_additional_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='economy_weight_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
