# Generated by Django 5.2.4 on 2025-08-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_wasterequest_economy_weight_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
