# Generated by Django 5.2.4 on 2025-09-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_wasterequestuserupdate_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequest',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
