# Generated by Django 5.2.4 on 2025-09-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_wasterequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestcancelled',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wasterequestcancelled',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasterequestcancelled',
            name='refund_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
