# Generated by Django 5.2.4 on 2025-09-02 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_wasterequestfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestfeedback',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequestfeedback',
            name='waste_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.wasterequest'),
        ),
        migrations.AlterUniqueTogether(
            name='wasterequestfeedback',
            unique_together={('waste_request', 'pickup_date', 'user')},
        ),
        migrations.RemoveField(
            model_name='wasterequestfeedback',
            name='pickup',
        ),
    ]