# Generated by Django 5.2.4 on 2025-09-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_wasterequestfeedback_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteRequestFeedback',
        ),
    ]
