# Generated by Django 5.2.4 on 2025-09-02 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_wasterequestfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WasteRequestFeedback',
            new_name='UserFeedback',
        ),
    ]
