# Generated by Django 5.2.4 on 2025-09-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_wasterequestfeedback_userfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
