# Generated by Django 5.2.4 on 2025-09-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
