# Generated by Django 5.2.4 on 2025-09-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_wasterequest_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
