# Generated by Django 5.2.4 on 2025-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_zip_code_userprofile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestcancelled',
            name='refund_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
