# Generated by Django 5.2.4 on 2025-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_wasterequestcancelled_refund_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestcancelled',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequestuserupdate',
            name='refund_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
