# Generated by Django 5.2.4 on 2025-09-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_wasterequestcancelled_refund_processed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasterequestcancelled",
            name="refund_status",
        ),
        migrations.RemoveField(
            model_name="wasterequestuserupdate",
            name="refund_status",
        ),
    ]
