# Generated by Django 5.2.4 on 2025-09-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_remove_wasterequestcancelled_refund_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasterequestcancelled",
            name="refund_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Refund_initiated", "Refund Initiated"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
