# Generated by Django 5.2.4 on 2025-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_wasterequestcancelled_refund_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sms_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
