# Generated by Django 5.2.4 on 2025-09-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_userprofile_email_notifications_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasterequest",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="staff.staff",
            ),
        ),
    ]
