# Generated by Django 5.2.4 on 2025-09-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_wasterequest_assigned_staff"),
        ("staff", "0002_area_staff_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasterequest",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.area",
            ),
        ),
    ]
