# Generated by Django 5.2.4 on 2025-09-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_wasterequest_area"),
        ("staff", "0002_area_staff_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasterequeststatus",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.area",
            ),
        ),
        migrations.AddField(
            model_name="wasterequeststatus",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staff",
            ),
        ),
    ]
