# Generated by Django 5.2.4 on 2025-09-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_wasterequeststatus_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectiondetail",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="collectiondetail",
            name="user",
        ),
        migrations.RemoveField(
            model_name="requestupdate",
            name="request",
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="WasteCategory",
        ),
        migrations.DeleteModel(
            name="CollectionDetail",
        ),
        migrations.DeleteModel(
            name="RequestUpdate",
        ),
        migrations.DeleteModel(
            name="StaffProfile",
        ),
    ]
