# Generated by Django 5.2.4 on 2025-09-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_remove_collectiondetail_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasterequeststatus",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
