# Generated by Django 5.2.4 on 2025-09-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_wasterequeststatus_is_paid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Refund",
        ),
    ]
