# Generated by Django 5.2.4 on 2025-09-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_wasterequestuserupdate_refund_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasterequestpickup",
            name="waste_request",
        ),
        migrations.DeleteModel(
            name="AdjustmentInvoice",
        ),
        migrations.DeleteModel(
            name="WasteRequestPickup",
        ),
    ]
