# Generated by Django 5.2.4 on 2025-09-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_remove_wasterequestpickup_waste_request_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wasterequestuserupdate",
            old_name="refund_amount",
            new_name="partial_refund_amount",
        ),
        migrations.RenameField(
            model_name="wasterequestuserupdate",
            old_name="refund_id",
            new_name="partial_refund_id",
        ),
        migrations.RenameField(
            model_name="wasterequestuserupdate",
            old_name="refund_processed_at",
            new_name="partial_refund_processed_at",
        ),
        migrations.RenameField(
            model_name="wasterequestuserupdate",
            old_name="refund_status",
            new_name="partial_refund_status",
        ),
    ]
