# Generated by Django 5.2.4 on 2025-09-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0052_rename_refund_amount_wasterequestuserupdate_partial_refund_amount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasterequest",
            name="area",
        ),
        migrations.RemoveField(
            model_name="wasterequest",
            name="assigned_staff",
        ),
        migrations.RemoveField(
            model_name="wasterequest",
            name="invoice_url",
        ),
    ]
