# Generated by Django 5.2.4 on 2025-09-21 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_wasterequest_area_and_more"),
        ("staff", "0005_delete_staffperformancesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasterequest",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.area",
            ),
        ),
        migrations.AddField(
            model_name="wasterequest",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staff",
            ),
        ),
    ]
