# Generated by Django 5.2.4 on 2025-09-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_wasterequest_area_wasterequest_assigned_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasterequest",
            name="receipt_file",
        ),
    ]
