# Generated by Django 5.2.4 on 2025-09-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_remove_wasterequest_receipt_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
