# Generated by Django 5.2.4 on 2025-09-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_delete_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
