# Generated by Django 5.2.4 on 2025-09-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "zipcodes",
                    models.TextField(
                        help_text="Comma-separated zipcodes for this area (e.g. 560001,560002)"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staff",
            name="areas",
            field=models.ManyToManyField(
                blank=True, related_name="staff", to="staff.area"
            ),
        ),
    ]
