# Generated by Django 5.2.4 on 2025-09-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_area_staff_areas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="email",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="phone",
        ),
    ]
