# Generated by Django 5.2.4 on 2025-09-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_remove_staff_email_remove_staff_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_pickups", models.IntegerField(default=0)),
                ("completed", models.IntegerField(default=0)),
                ("assigned", models.IntegerField(default=0)),
                ("on_the_way", models.IntegerField(default=0)),
                ("cancelled", models.IntegerField(default=0)),
                (
                    "cod_to_collect",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("tasks_total", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("status_distribution", models.JSONField(default=list)),
                ("completion_trend", models.JSONField(default=list)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to="staff.staff",
                    ),
                ),
            ],
        ),
    ]
