# Generated by Django 5.2.4 on 2025-09-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_staffperformancesnapshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaffPerformanceSnapshot",
        ),
    ]
