# Generated by Django 5.2.4 on 2025-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_delete_staffperformancesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
